import {test,expect,session} from './fixtures';
test.use({storageState:async({},use)=>{await use({cookies:[{name:'sakuya_session',value:session('user'),domain:'127.0.0.1',path:'/',expires:-1,httpOnly:true,secure:false,sameSite:'Lax'}],origins:[]});}});
const headers={'X-Sakuya-Client':'workspace'};
async function seed(request:any){const data=await(await request.get('/api/planner')).json();const list=data.lists[0];const other=await(await request.post('/api/planner/lists',{headers,data:{name:'默认工作日历'}})).json();const task=await(await request.post('/api/planner/entries',{headers,data:{title:'菜单测试任务',list_id:list.id}})).json();return{task,list,other};}
test('任务鼠标菜单、详细日期、标签、置顶、子任务、放弃和笔记',async({page,request})=>{
 const {task}=await seed(request);await page.goto('/#todos');const row=page.locator(`[data-task-id="${task.id}"]`);
 async function menu(){await row.click({button:'right',position:{x:160,y:30}});return page.getByRole('menu',{name:'任务选项'});}
 let m=await menu();await expect(m).toBeVisible();await page.screenshot({path:'test-results/task-context-menu.png'});await expect(m.getByRole('menuitem',{name:'开始专注'})).toHaveCount(0);const r=(await row.boundingBox())!,b=(await m.boundingBox())!;expect(Math.abs(b.x-r.x-166)).toBeLessThan(2);
 await m.getByRole('menuitem',{name:'高优先级',exact:true}).click();await expect(row.locator('.task-check')).toHaveClass(/priority-high/);
 m=await menu();await m.getByRole('menuitem',{name:'详细日期'}).click();const date=page.getByRole('dialog',{name:'详细日期'});await date.getByLabel('开始',{exact:true}).fill('2026-10-01T09:00');await date.getByLabel('结束',{exact:true}).fill('2026-10-01T10:30');await date.getByRole('button',{name:'保存',exact:true}).click();await expect(row.locator('time')).toContainText('09:00');
 m=await menu();await m.getByRole('menuitem',{name:'标签',exact:true}).click();await page.getByRole('dialog',{name:'标签',exact:true}).getByLabel('标签',{exact:true}).fill('工作,重要');await page.getByRole('dialog',{name:'标签',exact:true}).getByRole('button',{name:'保存'}).click();await expect(row).toContainText('#重要');
 m=await menu();await m.getByRole('menuitem',{name:'置顶',exact:true}).click();await expect(page.locator('.task-group-pinned')).toContainText('菜单测试任务');
 m=await menu();await m.getByRole('menuitem',{name:'添加子任务'}).click();const editor=page.getByRole('dialog',{name:'新建任务'});await editor.getByLabel('标题',{exact:true}).fill('准备子任务');await editor.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.task-subtask')).toContainText('准备子任务');
 m=await menu();await m.getByRole('menuitem',{name:'放弃',exact:true}).click();await expect(row).not.toBeVisible();await page.locator('.task-group-cancelled .task-group-heading').click();await expect(row).toBeVisible();
 m=await menu();await m.getByRole('menuitem',{name:'恢复任务'}).click();await expect(row).toBeVisible();m=await menu();await m.getByRole('menuitem',{name:'转换为笔记'}).click();await page.getByRole('button',{name:'笔记',exact:true}).click();await expect(row.locator('.task-note-mark')).toBeVisible();await expect(row.locator('.task-check')).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'笔记',exact:true}).click();await expect(row).toContainText('#重要');
 await page.screenshot({path:'test-results/task-note-state.png'});
});
test('任务菜单移动、副本和删除',async({page,request})=>{
 const {task,other}=await seed(request);await page.goto('/#todos');const row=page.locator(`[data-task-id="${task.id}"]`);await row.click({button:'right'});await page.getByRole('menuitem',{name:'移动到'}).click();await page.getByRole('menuitem',{name:other.name}).click();await expect(row.locator('.task-list-caption')).toHaveText(other.name);
 await row.click({button:'right'});await page.getByRole('menuitem',{name:'创建副本'}).click();await expect(page.locator('.todo-row').filter({hasText:'菜单测试任务（副本）'})).toBeVisible();await row.click({button:'right'});await page.getByRole('menuitem',{name:'删除',exact:true}).click();await expect(row).toHaveCount(0);await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(row).toBeVisible();
});
test('默认日历、空白创建菜单与时间块重命名删除',async({page,request})=>{
 const {other}=await seed(request);await page.goto('/#calendar');await page.getByRole('button',{name:'我的规划',exact:true}).click();await page.getByRole('button',{name:other.name,exact:true}).click({button:'right'});await page.getByRole('button',{name:'设为默认',exact:true}).click();await expect(page.getByRole('button',{name:'设为默认',exact:true})).toHaveAttribute('aria-pressed','true');await page.reload();await page.getByRole('button',{name:'我的规划',exact:true}).click();await page.getByRole('button',{name:other.name,exact:true}).click({button:'right'});await expect(page.getByRole('button',{name:'设为默认',exact:true})).toHaveAttribute('aria-pressed','true');await page.keyboard.press('Escape');
 const column=page.locator('.calendar-day').first();const box=(await column.boundingBox())!,scroll=(await page.locator('.calendar-scroll').boundingBox())!;await page.mouse.click(box.x+box.width/2,scroll.y+90,{button:'right'});await page.getByRole('menuitem',{name:'创建',exact:true}).click();const editor=page.getByRole('dialog',{name:'新建日程'});await expect(editor.getByLabel('所属清单')).toHaveValue(other.id);await editor.getByLabel('标题',{exact:true}).fill('默认清单时间块');await editor.getByRole('button',{name:'保存',exact:true}).click();const event=page.locator('.calendar-event').filter({hasText:'默认清单时间块'});await expect(event).toBeVisible();await event.click({button:'right'});await page.getByRole('menuitem',{name:'重命名',exact:true}).click();const rename=page.getByRole('dialog',{name:'重命名',exact:true});await rename.getByLabel('标题').fill('已修改的时间块');await rename.getByRole('button',{name:'保存'}).click();const changed=page.locator('.calendar-event').filter({hasText:'已修改的时间块'});await expect(changed).toBeVisible();await changed.click({button:'right'});await page.getByRole('menuitem',{name:'删除',exact:true}).click();await expect(changed).toHaveCount(0);
 // Left-drag creation must use the same persisted default.
 await page.mouse.move(box.x+box.width/2,scroll.y+160);await page.mouse.down();await page.mouse.move(box.x+box.width/2,scroll.y+210,{steps:8});await page.mouse.up();await expect(page.getByRole('dialog',{name:'新建日程'}).getByLabel('所属清单')).toHaveValue(other.id);
});
test('已识别 OAuth 配置直接打开浏览器授权并显示导入结果',async({page})=>{
 const status={google:{configured:true,connected:false,client_id:'test-client',secret_set:false,redirect_uri:'http://127.0.0.1:8120/api/integrations/google/callback'},dida:{configured:false,connected:false},ticktick:{configured:false,connected:false}};
 await page.route('**/api/integrations',r=>r.fulfill({json:status}));await page.route('**/api/integrations/google/connect',r=>r.fulfill({json:{url:'https://accounts.google.com/o/oauth2/v2/auth?test=1'}}));await page.context().route('https://accounts.google.com/**',r=>r.fulfill({body:'Test authorization page'}));await page.goto('/#settings');const row=page.locator('.integration-setting-row').filter({has:page.getByText('Google 日历',{exact:true})});await expect(row).toContainText('已识别连接配置');const popupPromise=page.waitForEvent('popup');await row.getByRole('button',{name:'浏览器连接并导入'}).click();const popup=await popupPromise;await popup.waitForURL('https://accounts.google.com/**');await expect(page.getByRole('status')).toContainText('请在浏览器授权');await popup.close();
});

test('Google 应用未注册时不再要求使用者填写开发者凭据',async({page})=>{
 await page.route('**/api/integrations',r=>r.fulfill({json:{google:{configured:false,connected:false},dida:{configured:false,connected:false},ticktick:{configured:false,connected:false}}}));
 await page.goto('/#settings');const row=page.locator('.integration-setting-row').filter({has:page.getByText('Google 日历',{exact:true})});
 await row.getByRole('button',{name:'浏览器连接并导入'}).click();
 const dialog=page.getByRole('dialog',{name:'连接 Google 日历'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('textbox')).toHaveCount(0);await expect(dialog.getByRole('button',{name:'使用 Google 账号登录'})).toBeDisabled();await expect(dialog).toContainText('需要开发者先完成应用注册');
});
