import {test, expect, session} from './fixtures';
test.use({storageState: async ({}, use) => { await use({cookies: [{name: 'sakuya_session', value: session('user'), domain: '127.0.0.1', path: '/', expires: -1, httpOnly: true, secure: false, sameSite: 'Lax'}], origins: []}); }});
const headers = {'X-Sakuya-Client': 'workspace'};

test('清单仅勾选框切换时间块，右键在鼠标旁编辑并设置默认，直接删除非空清单', async ({page, request}) => {
  const listing = await (await request.post('/api/planner/lists', {headers, data: {name: '交互清单'}})).json();
  await page.goto('/#calendar');
  await page.getByRole('button', {name: '我的规划', exact: true}).click();
  const day = await page.locator('.calendar-day').first().getAttribute('data-date');
  await request.post('/api/planner/entries', {headers, data: {title: '清单时间块', list_id: listing.id, kind: 'event', start: day + 'T09:00:00+08:00', end: day + 'T10:00:00+08:00'}});
  await request.post('/api/planner/entries', {headers, data: {title: '清单任务', list_id: listing.id}});
  await page.reload();
  await page.getByRole('button', {name: '我的规划', exact: true}).click();
  const name = page.getByRole('button', {name: listing.name, exact: true});
  const checkbox = page.getByRole('checkbox', {name: '显示清单 ' + listing.name});
  const event = page.locator('.calendar-event').filter({hasText: '清单时间块'});
  await expect(event).toHaveCount(1);
  await name.click(); await expect(event).toHaveCount(1);
  await checkbox.click(); await expect(event).toHaveCount(0);
  await name.click(); await expect(event).toHaveCount(0);
  await checkbox.click(); await expect(event).toHaveCount(1);
  await name.click({button: 'right', position: {x: 35, y: 15}});
  const dialog = page.getByRole('dialog', {name: '编辑清单'});
  await expect(dialog).toBeVisible();
  await expect(checkbox).toBeChecked();
  const rowBox = (await name.boundingBox())!, box = (await dialog.boundingBox())!;
  expect(Math.min(Math.abs(box.x + box.width - (rowBox.x + 35)), Math.abs(box.x - (rowBox.x + 35)))).toBeLessThanOrEqual(14);
  expect(box.x).toBeGreaterThanOrEqual(0); expect(box.y).toBeGreaterThanOrEqual(0);
  await page.screenshot({path: 'test-results/list-editor-popover.png', animations: 'disabled'});
  await dialog.getByRole('button', {name: '设为默认', exact: true}).click();
  await expect(dialog.getByRole('button', {name: '设为默认', exact: true})).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('Escape'); await expect(dialog).toBeHidden();
  await name.click({button: 'right'});
  await dialog.getByRole('button', {name: '删除', exact: true}).click();
  await expect(name).toHaveCount(0); await expect(event).toHaveCount(0);
  await expect(page.getByText('请先移出或删除清单中的任务和日程')).toHaveCount(0);
  const state = await (await request.get('/api/planner')).json();
  expect(state.entries.filter((entry: any) => entry.list_id === listing.id)).toHaveLength(0);
  expect(state.preferences.default_calendar_list).toBe('');
});

test('清单鼠标拖动顺序刷新后保留，任务页共用顺序且右键可编辑', async ({page, request}) => {
  const first = (await (await request.get('/api/planner')).json()).lists[0];
  const second = await (await request.post('/api/planner/lists', {headers, data: {name: '第二清单'}})).json();
  const third = await (await request.post('/api/planner/lists', {headers, data: {name: '第三清单'}})).json();
  await page.goto('/#calendar'); await page.getByRole('button', {name: '我的规划', exact: true}).click();
  const rows = page.locator('[data-list-id]');
  await page.getByRole('button', {name: third.name, exact: true}).dragTo(page.locator(`[data-list-id="${first.id}"]`), {targetPosition: {x: 80, y: 2}});
  await expect(rows.first()).toHaveAttribute('data-list-id', third.id);
  await expect.poll(async () => (await (await request.get('/api/planner')).json()).preferences.list_order).toEqual([third.id, first.id, second.id]);
  await page.reload(); await page.getByRole('button', {name: '我的规划', exact: true}).click();
  await expect(rows.first()).toHaveAttribute('data-list-id', third.id);
  await page.goto('/#todos'); await expect(rows.first()).toHaveAttribute('data-list-id', third.id);
  const secondRow = page.locator(`[data-list-id="${second.id}"]`), box = (await secondRow.boundingBox())!;
  await page.getByRole('button', {name: third.name, exact: true}).dragTo(secondRow, {targetPosition: {x: 80, y: box.height - 2}});
  await expect(rows.last()).toHaveAttribute('data-list-id', third.id);
  await expect.poll(async () => (await (await request.get('/api/planner')).json()).preferences.list_order).toEqual([first.id, second.id, third.id]);
  await page.getByRole('button', {name: third.name, exact: true}).click({button: 'right'});
  const dialog = page.getByRole('dialog', {name: '编辑清单'});
  await dialog.getByLabel('清单名称').fill('第三清单改名');
  await dialog.getByRole('button', {name: '保存清单'}).click();
  await expect(rows.last()).toHaveAttribute('data-list-id', third.id);
  await expect(rows.last()).toContainText('第三清单改名');
  await page.getByRole('button', {name: '第三清单改名', exact: true}).click({button: 'right'});
  await page.getByRole('button', {name: '第二清单', exact: true}).click();
  await expect(dialog).toBeHidden();
});
