import { _electron as electron } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results', { recursive: true });
const environment = { ...process.env, SAKUYA_DEV_URL: 'http://127.0.0.1:5173', SAKUYA_TEST: '1' };
const packaged = process.argv.includes('--packaged');
if (packaged) delete environment.SAKUYA_DEV_URL;
delete environment.ELECTRON_RUN_AS_NODE;
environment.NO_PROXY = '127.0.0.1,localhost';
environment.NODE_USE_ENV_PROXY = '0';
delete environment.HTTP_PROXY;
delete environment.HTTPS_PROXY;
delete environment.ALL_PROXY;
console.log('Launching desktop smoke test');
const app = await electron.launch({ args: packaged ? [] : ['.'], executablePath: packaged ? 'release/win-unpacked/Sakuya Agent.exe' : undefined, env: environment, timeout: 15000 });
console.log('Electron launched');
const win = await app.firstWindow();
console.log('Desktop window created');
win.setDefaultTimeout(15000);
await win.getByRole('heading', { name: '今天有什么想聊的？' }).waitFor();
await win.getByRole('button', { name: '选择助手，当前：聊天助手' }).click();
await win.getByRole('dialog', { name: '选择助手' }).getByRole('button', { name: /深度研究/ }).click();
await win.getByRole('button', { name: '工作', exact: true }).click();
await win.getByRole('heading', { name: '深度研究', exact: true }).waitFor();
await win.getByRole('button', { name: '新建深度研究', exact: true }).click();
await win.getByRole('dialog').waitFor();
await win.screenshot({ path: packaged ? 'test-results/desktop-packaged.png' : 'test-results/desktop.png' });
const security = await app.evaluate(({ BrowserWindow }) => {
  const prefs = BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();
  return { sandbox: prefs.sandbox, contextIsolation: prefs.contextIsolation, nodeIntegration: prefs.nodeIntegration };
});
console.log(JSON.stringify({ desktop: 'passed', packaged, security }));
await app.close();
