import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('heading', { name: '今天有什么想聊的？' }).waitFor();
await page.screenshot({ path: 'test-results/overview.png', fullPage: true, animations: 'disabled' });
await page.getByRole('button', { name: '选择助手，当前：聊天助手' }).click();
await page.screenshot({ path: 'test-results/assistants.png', animations: 'disabled' });
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'test-results/mobile-chat.png', animations: 'disabled' });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.goto('http://127.0.0.1:5173/#run/run_example_research');
await page.getByRole('heading', { name: '研究摘要' }).waitFor();
await page.screenshot({ path: 'test-results/report.png', fullPage: true, animations: 'disabled' });
await page.goto('http://127.0.0.1:5173/#tickets');
await page.getByRole('heading', { name: '技术支持工单' }).waitFor();
await page.screenshot({ path: 'test-results/tickets.png', fullPage: true, animations: 'disabled' });
console.log(JSON.stringify({ errors, screenshots: ['overview.png', 'report.png', 'tickets.png'] }));
await browser.close();
