import { useLocale, tr } from './i18n';
import { useState } from 'react';
import { Plus, Settings2, Trash2 } from 'lucide-react';
import { api } from './api';
import type { PageProps } from './pages';
import type { ModelProvider } from './types';
import { Field, PageHeader } from './ui';

export default function ModelSettings({ workspace, refresh, toast }: PageProps) {
  useLocale();
  const settings = workspace.settings;
  const [editing, setEditing] = useState<string | null>(null), [name, setName] = useState(''), [base, setBase] = useState(''), [key, setKey] = useState('');
  const [provider, setProvider] = useState(settings.providers[0]?.id || ''), [available, setAvailable] = useState<string[]>([]), [model, setModel] = useState(''), [reasoning, setReasoning] = useState(false);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [searchKey, setSearchKey] = useState('');
  async function action(fn: () => Promise<void>) { setBusy(true); setMessage(''); try { await fn(); refresh(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }
  async function discover(id: string) { setAvailable([]); const result = await api<{ models: string[] }>(`/settings/providers/${id}/models`); setAvailable(result.models); setMessage(result.models.length ? tr("已加载 {0} 个模型，可选择并添加。", [result.models.length]) : tr("供应商没有返回模型，可以手动填写模型 ID。")); }
  function edit(p: ModelProvider) { setEditing(p.id); setName(p.name); setBase(p.base_url); setKey(''); }
  return <><PageHeader icon={<Settings2 size={28} />} title={tr("设置")} description={tr("添加多个模型供应商，选择聊天中可用的模型。")} />
    <div className="provider-settings"><section className="settings-section"><h2>{tr("API 供应商")}</h2><p className="muted">{tr("支持 Chat Completions 兼容接口；自动读取供应商的 /models 列表。")}</p>
      <div className="provider-list">{settings.providers.map(p => <div className="provider-row" key={p.id}><div><strong>{p.name}</strong><small>{p.base_url}</small></div><button className="button small" disabled={busy} onClick={() => edit(p)}>{tr("编辑")}</button><button aria-label={tr("删除供应商 {0}", [p.name])} className="icon-button" disabled={busy} onClick={() => void action(async () => { await api(`/settings/providers/${p.id}`, 'DELETE'); if (provider === p.id) { setProvider(''); setAvailable([]); } if (editing === p.id) { setEditing(null); setName(''); setBase(''); setKey(''); } })}><Trash2 size={16} /></button></div>)}</div>
      <form onSubmit={e => { e.preventDefault(); void action(async () => { const result = await api<{ id: string }>('/settings/providers', 'POST', { id: editing, name, base_url: base, api_key: key }); setKey(''); setEditing(null); setName(''); setBase(''); setProvider(result.id); refresh(); toast("供应商已保存"); await discover(result.id); }); }}>
        <Field label={tr("供应商名称")}><input required value={name} onChange={e => setName(e.target.value)} placeholder={tr("例如：DeepSeek、私有模型服务")} /></Field><Field label={tr("API 根地址")}><input type="url" required value={base} onChange={e => setBase(e.target.value)} placeholder="https://provider.example/v1" /></Field><Field label="API Key" hint={editing ? tr("留空保留密钥；修改地址时须重新填写密钥。") : tr("密钥仅保存在本机，不会回传到浏览器。")}><input aria-label="API Key" type="password" autoComplete="new-password" required={!editing} value={key} onChange={e => setKey(e.target.value)} /></Field>
        <div className="settings-actions">{editing && <button type="button" className="button" onClick={() => { setEditing(null); setName(''); setBase(''); setKey(''); }}>{tr("取消编辑")}</button>}<button className="button primary" disabled={busy}><Plus size={15} />{editing ? tr("保存并加载模型") : tr("添加并加载模型")}</button></div></form>
    </section><section className="settings-section"><h2>{tr("聊天模型列表")}</h2><Field label={tr("选择供应商")}><select value={provider} onChange={e => { const id = e.target.value; setProvider(id); setModel(''); setAvailable([]); if (id) void action(() => discover(id)); }}><option value="">{tr("请选择供应商")}</option>{settings.providers.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
      <button className="button small" disabled={busy || !provider} onClick={() => void action(() => discover(provider))}>{tr("重新加载模型")}</button><Field label={tr("模型 ID")} hint={tr("从自动加载的列表选择，或手动输入模型 ID。")}><input aria-label={tr("模型 ID")} list="discovered-models" value={model} onChange={e => setModel(e.target.value)} placeholder={tr("选择或输入模型")} /><datalist id="discovered-models">{available.map(m => <option key={m} value={m} />)}</datalist></Field><label className="check-row"><input type="checkbox" checked={reasoning} onChange={e => setReasoning(e.target.checked)} />{tr("此模型支持 reasoning_effort（低 / 中 / 高）")}</label><p className="muted">{tr("只有供应商明确支持此参数的模型才勾选；其他模型使用默认强度。")}</p>
      <button className="button primary" disabled={busy || !provider || !model.trim()} onClick={() => void action(async () => { await api('/settings/models', 'POST', { provider_id: provider, name: model, reasoning }); setModel(''); toast("已加入聊天模型列表"); })}>{tr("添加到模型列表")}</button>
      <div className="model-list">{settings.models.map(m => <div className="provider-row" key={m.id}><div><strong>{m.name}</strong><small>{settings.providers.find(p => p.id === m.provider_id)?.name} · {m.reasoning ? tr("可调思考强度") : tr("默认思考强度")}</small></div><button className="button small" disabled={busy || settings.default_model_id === m.id} onClick={() => void action(async () => { await api('/settings/default-model', 'PUT', { model_id: m.id }); })}>{settings.default_model_id === m.id ? tr("默认") : tr("设为默认")}</button><button className="icon-button" aria-label={tr("删除模型 {0}", [m.name])} disabled={busy} onClick={() => void action(async () => { await api(`/settings/models/${m.id}`, 'DELETE'); })}><Trash2 size={15} /></button></div>)}</div>
    </section><section className="settings-section"><h2>{tr("联网搜索")}</h2><Field label="Tavily API Key"><input type="password" autoComplete="new-password" placeholder={settings.search_configured ? tr("已配置；输入可替换") : tr("可选")} value={searchKey} onChange={e => setSearchKey(e.target.value)} /></Field><button className="button" disabled={busy || !searchKey} onClick={() => void action(async () => { await api('/settings/search', 'PUT', { search_key: searchKey }); setSearchKey(''); toast("搜索配置已保存"); })}>{tr("保存搜索配置")}</button></section></div>
    {message && <p role="status" className="settings-message">{tr(message)}</p>}
  </>;
}
