import { useLocale, tr } from './i18n';
import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { ArrowRight, Plus, Search, ListFilter, ArrowDownUp, FlaskConical, Ticket as TicketIcon, Clock3, CircleCheck, BookOpen, FileText, Download, RotateCcw, Square, Check, SkipForward, ChevronLeft, ChevronRight, LayoutGrid, List, LoaderCircle, ShieldCheck, Pencil, Terminal, } from 'lucide-react';
import type { Workspace, Run, RunKind, Project, ModalState, Navigate, RunEvent } from './types';
import { api, download } from './api';
import { PageHeader, Fold, SectionTitle, Status, Demo, Empty, KindIcon, kindLabels, date, time, ticketLabels, Loading, External, Field } from './ui';

export interface PageProps { workspace: Workspace; projectId: string; navigate: Navigate; open: (modal: ModalState) => void; refresh: () => void; toast: (text: string) => void; selectProject: (id: string) => void }
const scoped = <T extends { project_id: string }>(items: T[], id: string) => id === 'all' ? items : items.filter(x => x.project_id === id);

export function RunTable({ runs, navigate }: { runs: Run[]; projects: Project[]; navigate: Navigate }) {
  useLocale();
  if (!runs.length) return <Empty title={tr("这里还没有任务")} description={tr("新建研究或诊断任务，过程与结果会保存在这里。")} />;
  return <div className="table-wrap"><table className="data-table"><thead><tr><th><FileText size={13} />{tr("任务名称")}</th><th>{tr("状态")}</th><th>{tr("更新时间")}</th><th /></tr></thead><tbody>{runs.map(r => <tr key={r.id} onClick={() => navigate(`run/${r.id}`)}><td><button className="table-title" onClick={e => { e.stopPropagation(); navigate(`run/${r.id}`); }}><span className={`row-icon ${r.kind}`}><KindIcon kind={r.kind} size={16} /></span><span>{r.title}</span>{r.mode === 'demo' && <Demo />}</button></td><td><Status value={r.status} /></td><td className="muted nowrap">{date(r.updated_at)}</td><td><ChevronRight size={14} className="muted" /></td></tr>)}</tbody></table></div>;
}

export function RunList({ kind, ...props }: PageProps & { kind: RunKind }) {
  useLocale();
  const [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [oldest, setOldest] = useState(false);
  const items = scoped(props.workspace.runs, props.projectId).filter(r => r.kind === kind);
  const runs = items.filter(r => r.title.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || r.status === status)).sort((a, b) => (oldest ? 1 : -1) * a.updated_at.localeCompare(b.updated_at));
  return <><PageHeader icon={<KindIcon kind={kind} size={30} />} eyebrow={kind === 'research' ? 'RESEARCH STUDIO' : 'ISSUE INVESTIGATION'} title={kindLabels[kind]} description={kind === 'research' ? tr("从资料到证据，从候选方案到有依据的决定。") : tr("结合代码、资料与实验，把问题一步步查清楚。")} actions={<button className="button primary" onClick={() => props.open({ type: 'run', kind })}><Plus size={16} />{tr("新建")}{kindLabels[kind]}</button>} /><div className="view-tabs"><button className="active"><List size={15} />{tr("全部任务")}<span>{items.length}</span></button><span className="view-tabs-note">{tr("研究过程与结果持续保存")}</span></div><div className="table-toolbar"><div className="search-input"><Search size={15} /><input placeholder={tr("搜索任务…")} aria-label={tr("搜索任务")} value={query} onChange={e => setQuery(e.target.value)} /></div><div className="toolbar-right"><label className="filter-select"><ListFilter size={14} /><select aria-label={tr("筛选任务状态")} value={status} onChange={e => setStatus(e.target.value)}><option value="all">{tr("所有状态")}</option><option value="running">{tr("进行中")}</option><option value="waiting">{tr("待确认")}</option><option value="completed">{tr("已完成")}</option><option value="failed">{tr("失败")}</option><option value="queued">{tr("排队中")}</option><option value="cancelled">{tr("已取消")}</option></select></label><button className="button subtle small" onClick={() => setOldest(!oldest)}><ArrowDownUp size={14} />{oldest ? tr("最早优先") : tr("最近更新")}</button></div></div><RunTable runs={runs} projects={props.workspace.projects} navigate={props.navigate} /></>;
}

export function RunDetail({ id, ...props }: PageProps & { id: string }) {
  useLocale();
  const [tab, setTab] = useState('report'), [sourceIndex, setSourceIndex] = useState<number | null>(null), [busy, setBusy] = useState(false);
  const query = useQuery({ queryKey: ['run', id], queryFn: () => api<Run & { events: RunEvent[] }>(`/runs/${id}`), refetchInterval: q => q.state.data && ['queued', 'running'].includes(q.state.data.status) ? 1500 : false });
  const run = query.data;
  useEffect(() => {
    if (!run || !['queued', 'running'].includes(run.status)) return;
    const stream = new EventSource(`/api/runs/${id}/events`);
    stream.addEventListener('progress', () => { void query.refetch(); });
    stream.addEventListener('status', e => { const value = JSON.parse((e as MessageEvent).data); if (!['queued', 'running'].includes(value.status)) { stream.close(); void query.refetch(); props.refresh(); } });
    return () => stream.close();
  }, [id, run?.status]);
  if (query.isLoading) return <Loading />;
  if (!run) return <Empty title={tr("无法打开任务")} description={query.error?.message || tr("任务不存在")} />;
  async function action(path: string, body?: unknown) {
    setBusy(true);
    try { await api(`/runs/${id}/${path}`, 'POST', body); await query.refetch(); props.refresh(); props.toast(path === 'save' ? tr("报告已保存到知识库") : tr("操作已保存")); } catch (e) { props.toast((e as Error).message); } finally { setBusy(false); }
  }
  const tabs = [{ key: 'report', name: tr("报告"), icon: FileText }, { key: 'plan', name: tr("研究计划"), icon: List }, { key: 'activity', name: tr("执行记录"), icon: Clock3 }, { key: 'experiment', name: tr("实验"), icon: Terminal }];
  return <><button className="back-link" onClick={() => props.navigate(run.kind)}><ChevronLeft size={14} />{kindLabels[run.kind]}</button><PageHeader icon={<KindIcon kind={run.kind} size={30} />} title={run.title} description="" actions={<>{run.report && <><a className="button small" href={`/api/runs/${id}/export`} download><Download size={15} />{tr("导出")}</a></>}{['queued', 'running', 'waiting'].includes(run.status) && <button className="button small" disabled={busy} onClick={() => action('cancel')}><Square size={13} />{tr("取消")}</button>}{run.status === 'failed' && <button className="button small" onClick={() => action('retry')} disabled={busy}><RotateCcw size={14} />{tr("重试")}</button>}</>} /><div className="detail-meta"><Status value={run.status} />{run.mode === 'demo' && <Demo />}<span><Clock3 size={13} />{date(run.created_at)} {time(run.created_at)}</span><span>{run.sources.length}{tr("份资料")}</span>{run.tokens > 0 && <span>{run.tokens.toLocaleString()} tokens</span>}{run.ticket_id && <button className="text-button" onClick={() => props.navigate(`ticket/${run.ticket_id}`)}><TicketIcon size={14} />{tr("关联工单")}</button>}</div>
    {run.mode === 'demo' && <div className="notice"><FlaskConical size={16} /><span>{tr("演示运行 · 报告用于体验工作流，没有调用外部模型或执行真实实验。")}</span></div>}
    {run.status === 'waiting' && <div className="approval-box"><div><ShieldCheck size={21} /><div><strong>{tr("等待批准")}</strong><p>{tr(run.approval?.message || "先检查「实验」中的代码，再决定执行或跳过。")}</p>{run.approval?.kind === 'sources' && <pre>{run.approval.script}</pre>}</div></div><div>{run.approval?.kind !== 'sources' && <button className="button" onClick={() => setTab('experiment')}>{tr("查看脚本")}</button>}<button className="button" disabled={busy} onClick={() => action('resume', { decision: 'skip' })}><SkipForward size={14} />{tr("拒绝")}</button><button className="button primary" disabled={busy} onClick={() => action('resume', { decision: 'approve' })}><Check size={15} />{tr("确认执行")}</button></div></div>}
    {run.error && <div role="alert" className="form-error">{tr(run.error)}</div>}
    <div className="view-tabs">{tabs.map(t => <button className={tab === t.key ? 'active' : ''} key={t.key} onClick={() => setTab(t.key)}><t.icon size={15} />{t.name}{t.key === 'activity' && <span>{run.events.length}</span>}</button>)}</div>
    {tab === 'report' && <div className="report-layout"><div className="report-main">{run.report ? <article className="markdown"><ReactMarkdown disallowedElements={['img']} remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => href?.startsWith('#source-') ? <button className="citation" onClick={() => setSourceIndex(Number(href.replace('#source-', '')) - 1)}>{children}</button> : <a href={href} target="_blank" rel="noreferrer">{children}</a> }}>{run.report.replace(/\[(\d+)\](?!\()/g, '[$1](#source-$1)')}</ReactMarkdown></article> : <div className="report-pending">{['queued', 'running'].includes(run.status) ? <LoaderCircle size={27} className="spin" /> : <FileText size={27} />}<h3>{run.status === 'waiting' ? tr("等待实验确认") : run.status === 'failed' ? tr("任务中断，尚未生成报告") : run.status === 'cancelled' ? tr("任务已取消") : tr("正在逐步整理你的问题")}</h3><p>{run.events.at(-1)?.message || tr("任务已保存，等待执行进程接收。")}</p><button className="button subtle" onClick={() => setTab('activity')}>{tr("查看执行记录")}<ArrowRight size={14} /></button></div>}</div><aside className="source-panel"><h3><BookOpen size={15} />{tr("资料与证据")}<span>{run.sources.length}</span></h3><p className="source-help">{tr("点击查看保存的原文片段")}</p>{run.sources.map((s, i) => <div className={`source-item ${sourceIndex === i ? 'expanded' : ''}`} key={`${s.url}-${i}`}><button aria-expanded={sourceIndex === i} onClick={() => setSourceIndex(sourceIndex === i ? null : i)}><span className="source-number">{i + 1}</span><span>{s.title}<small>{s.type === 'search_excerpt' ? tr("搜索摘要 · 未读取完整原文") : s.type === 'code' ? tr("仓库代码") : s.type === 'demo' ? tr("演示输入") : s.url ? new URL(s.url).hostname : tr("项目资料")}</small></span><ChevronRight size={13} /></button><Fold open={sourceIndex === i}><div className="source-content"><pre>{s.content}</pre>{s.url && <External href={s.url}>{tr("打开原文")}</External>}</div></Fold></div>)}{!run.sources.length && <p className="muted source-empty">{tr("资料将在收集完成后显示。")}</p>}</aside></div>}
    {tab === 'plan' && <div className="plan-content"><div className="brief-box"><span className="small-label">{tr("原始问题")}</span><p>{run.prompt}</p></div><h3>{tr("任务计划")}</h3>{run.plan.map((step, i) => <div className="plan-step" key={i}><span>{i + 1}</span><p>{step}</p>{run.status === 'completed' && <CircleCheck size={16} />}</div>)}{!run.plan.length && <p className="muted">{tr("执行进程生成计划后将在这里显示。")}</p>}</div>}
    {tab === 'activity' && <div className="timeline">{run.events.map(e => <div className={`timeline-item ${e.stage}`} key={e.seq}><span className="timeline-dot" /><span className="timeline-time">{time(e.created_at)}</span><div><strong>{({ plan: tr("制定计划"), collect: tr("资料收集"), assess: tr("证据检查"), experiment: tr("实验验证"), report: tr("整理报告"), completed: tr("运行完成"), approval: tr("人工确认"), warning: tr("需要关注"), failed: tr("运行失败"), recovery: tr("恢复任务"), cancelled: tr("任务取消") } as Record<string, string>)[e.stage] || e.stage}</strong><p>{e.message}</p></div></div>)}{!run.events.length && <Empty title={tr("还没有执行记录")} description={tr("任务开始后，会在这里记录各步骤的结果。")} />}</div>}
    {tab === 'experiment' && (run.script ? <div className="experiment-content"><div className="notice"><ShieldCheck size={16} />{tr("仅标准库最小实验 · 禁止网络 · 60 秒上限 · 不等同于完整仓库测试")}</div><pre className="code-block"><code>{run.script}</code></pre>{run.experiment_result && <><h3>{tr("运行结果")}</h3><pre className="code-block">{run.experiment_result}</pre></>}</div> : <Empty title={tr("这项任务还没有实验")} description={tr("创建任务时勾选「生成最小验证实验」，脚本会在执行前交给你审核。")} icon={<Terminal size={25} />} />)}
  </>;
}

export function Tickets(props: PageProps) {
  useLocale();
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('all'), [board, setBoard] = useState(false);
  const all = scoped(props.workspace.tickets, props.projectId);
  const tickets = all.filter(t => t.title.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || t.status === filter));
  return <><PageHeader icon={<TicketIcon size={30} />} eyebrow="SUPPORT DESK" title={tr("技术支持工单")} description={tr("从一条反馈开始，跟进调查、协作与解决。")} actions={<button className="button primary" onClick={() => props.open({ type: 'ticket' })}><Plus size={16} />{tr("新建工单")}</button>} /><div className="view-tabs"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>{tr("全部工单")}<span>{all.length}</span></button>{Object.entries(ticketLabels).map(([key, label]) => <button className={filter === key ? 'active' : ''} key={key} onClick={() => setFilter(key)}>{label}<span>{all.filter(x => x.status === key).length}</span></button>)}</div><div className="table-toolbar"><div className="search-input"><Search size={15} /><input aria-label={tr("搜索工单")} placeholder={tr("搜索工单…")} value={query} onChange={e => setQuery(e.target.value)} /></div><div className="segmented"><button aria-label={tr("表格视图")} className={!board ? 'active' : ''} onClick={() => setBoard(false)}><List size={16} /></button><button aria-label={tr("看板视图")} className={board ? 'active' : ''} onClick={() => setBoard(true)}><LayoutGrid size={16} /></button></div></div>{!tickets.length ? <Empty title={tr("没有符合条件的工单")} description={tr("尝试其他筛选条件，或记录一个新问题。")} /> : board ? <div className="kanban">{Object.entries(ticketLabels).map(([status, label]) => <div className="kanban-column" key={status}><h3><span className={`board-dot ${status}`} />{label}<span>{tickets.filter(t => t.status === status).length}</span></h3>{tickets.filter(t => t.status === status).map(t => <button className="kanban-card" key={t.id} onClick={() => props.navigate(`ticket/${t.id}`)}><small>{t.id.slice(-6).toUpperCase()}{t.is_demo && <Demo seed />}</small><strong>{t.title}</strong><p>{t.customer}</p><span className={`priority priority-${t.priority}`}>{({ high: tr("高优先级"), normal: tr("普通"), low: tr("低优先级") })[t.priority]}</span></button>)}</div>)}</div> : <div className="table-wrap"><table className="data-table tickets-table"><thead><tr><th>{tr("工单名称")}</th><th>{tr("状态")}</th><th>{tr("优先级")}</th><th>{tr("提交人")}</th><th>{tr("负责人")}</th><th>{tr("更新")}</th></tr></thead><tbody>{tickets.map(t => <tr key={t.id} onClick={() => props.navigate(`ticket/${t.id}`)}><td><button className="table-title" onClick={e => { e.stopPropagation(); props.navigate(`ticket/${t.id}`); }}><TicketIcon size={16} className="muted" /><span>{t.title}</span>{t.is_demo && <Demo seed />}</button></td><td><Status value={t.status} ticket /></td><td><span className={`priority priority-${t.priority}`}>{({ high: tr("高"), normal: tr("普通"), low: tr("低") })[t.priority]}</span></td><td className="muted">{t.customer}</td><td className="muted">{t.assignee}</td><td className="muted nowrap">{date(t.updated_at)}</td></tr>)}</tbody></table></div>}</>;
}

export function TicketDetail({ id, ...props }: PageProps & { id: string }) {
  useLocale();
  const ticket = props.workspace.tickets.find(t => t.id === id);
  const admin = props.workspace.user.role === 'admin';
  const [reply, setReply] = useState(''), [internal, setInternal] = useState(false), [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState(false), [title, setTitle] = useState(ticket?.title || ''), [description, setDescription] = useState(ticket?.description || '');
  if (!ticket) return <Empty title={tr("未找到工单")} description={tr("返回工单列表查看其他内容。")} />;
  async function patch(changes: object) { setBusy(true); try { await api(`/tickets/${id}`, 'PATCH', changes); props.refresh(); setEditing(false); props.toast("工单已更新"); } catch (e) { props.toast((e as Error).message); } finally { setBusy(false); } }
  async function send() { if (!reply.trim()) return; setBusy(true); try { await api(`/tickets/${id}/comments`, 'POST', { content: reply, internal }); setReply(''); props.refresh(); props.toast(internal ? tr("内部备注已保存") : tr("回复已发送，用户可在工单中查看")); } catch (e) { props.toast((e as Error).message); } finally { setBusy(false); } }
  return <><button className="back-link" onClick={() => props.navigate('tickets')}><ChevronLeft size={14} />{tr("技术支持工单")}</button>
    <PageHeader icon={<TicketIcon size={30} />} title={ticket.title} description={tr("由 {0} 提交 · {1}", [ticket.customer, date(ticket.created_at)])} actions={<><button className="button" onClick={() => { setTitle(ticket.title); setDescription(ticket.description); setEditing(true); }}>{tr("编辑工单")}</button>{admin && <button className="button primary" disabled={busy} onClick={() => void patch({ assignee: props.workspace.user.username, status: 'in_progress' })}>{tr("接受工单")}</button>}</>} />
    {admin ? <div className="ticket-properties"><Field label={tr("工单状态")}><select aria-label={tr("工单状态")} value={ticket.status} disabled={busy} onChange={e => void patch({ status: e.target.value })}>{Object.entries(ticketLabels).map(([key, value]) => <option value={key} key={key}>{value}</option>)}</select></Field><Field label={tr("优先级")}><select aria-label={tr("工单优先级")} value={ticket.priority} disabled={busy} onChange={e => void patch({ priority: e.target.value })}><option value="low">{tr("低")}</option><option value="normal">{tr("普通")}</option><option value="high">{tr("高")}</option></select></Field><Field label={tr("负责人")}><span>{ticket.assignee}</span></Field></div> : <div className="detail-meta"><Status value={ticket.status} ticket /><span>{tr("负责人：")}{ticket.assignee}</span></div>}
    {editing ? <form className="editor-form" onSubmit={e => { e.preventDefault(); void patch({ title, description }); }}><Field label={tr("工单标题")}><input required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label={tr("问题描述")}><textarea maxLength={16000} rows={6} value={description} onChange={e => setDescription(e.target.value)} /></Field><div className="settings-actions"><button type="button" className="button" onClick={() => setEditing(false)}>{tr("取消")}</button><button className="button primary" disabled={busy}>{tr("保存工单")}</button></div></form> : <article className="markdown ticket-description"><ReactMarkdown disallowedElements={['img']} remarkPlugins={[remarkGfm]}>{ticket.description}</ReactMarkdown></article>}
    <SectionTitle title={tr("处理记录")} detail={tr("{0} 条记录", [ticket.comments.length])} /><div className="comment-list">{ticket.comments.map(c => <div className="comment" key={c.id}><span className="avatar">S</span><div><div className="comment-meta"><strong>{c.author}</strong><span>{c.internal ? tr("内部备注") : tr("管理员回复")}</span><small>{date(c.created_at)} {time(c.created_at)}</small></div><p>{c.content}</p></div></div>)}</div>
    {admin && <div className="reply-editor"><div className="reply-tabs"><button className={!internal ? 'active' : ''} onClick={() => setInternal(false)}>{tr("回复用户")}</button><button className={internal ? 'active' : ''} onClick={() => setInternal(true)}>{tr("内部备注")}</button></div><textarea aria-label={tr("处理记录内容")} maxLength={16000} value={reply} onChange={e => setReply(e.target.value)} rows={4} placeholder={internal ? tr("仅管理员可见的处理备注…") : tr("输入回复，发送后用户可在工单中查看…")} /><div><span>{internal ? tr("仅管理员可见") : tr("发送到工单，不发送邮件通知")}</span><button className="button primary small" disabled={!reply.trim() || busy} onClick={() => void send()}>{internal ? tr("保存备注") : tr("发送回复")}</button></div></div>}
  </>;
}

export function Knowledge(props: PageProps) {
  useLocale();
  const [query, setQuery] = useState('');
  const docs = scoped(props.workspace.documents, props.projectId).filter(d => d.title.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader icon={<BookOpen size={30} />} eyebrow="SHARED KNOWLEDGE" title={tr("项目知识库")} description={tr("把资料、经验与研究结果留在这里，让下一次调查更有依据。")} actions={<button className="button primary" onClick={() => props.open({ type: 'document' })}><Plus size={16} />{tr("添加资料")}</button>} /><div className="table-toolbar"><div className="search-input"><Search size={15} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={tr("搜索资料…")} aria-label={tr("搜索资料")} /></div><span className="muted">{docs.length}{tr("份资料")}</span></div><div className="document-grid">{docs.map(d => <button className="document-card" key={d.id} onClick={() => props.navigate(`document/${d.id}`)}><div className="document-preview"><FileText size={27} strokeWidth={1.2} /><span>{d.content.replace(/[#*>`\[\]]/g, '').slice(0, 115)}</span></div><div className="document-info"><h3>{d.title}</h3><p>{d.source}{d.is_demo && <Demo />}<span>{date(d.updated_at)}</span></p></div></button>)}</div>{!docs.length && <Empty title={tr("让项目资料有一个家")} description={tr("导入 Markdown，或者把完成的研究报告保存到这里。")} />}</>;
}

export function DocumentDetail({ id, ...props }: PageProps & { id: string }) {
  useLocale();
  const doc = props.workspace.documents.find(d => d.id === id);
  if (!doc) return <Empty title={tr("未找到资料")} description={tr("返回知识库查看其他资料。")} />;
  return <><button className="back-link" onClick={() => props.navigate('knowledge')}><ChevronLeft size={14} />{tr("知识库")}</button><PageHeader icon={<FileText size={30} />} title={doc.title} description={tr("{0} · 更新于 {1}", [doc.source, date(doc.updated_at)])} actions={<><button className="button small" onClick={() => props.open({ type: 'document', document: doc })}><Pencil size={14} />{tr("编辑")}</button><button className="button small" onClick={() => download(doc.title + '.md', doc.content)}><Download size={14} />{tr("导出")}</button></>} />{doc.is_demo && <div className="notice">{tr("这份资料来自演示运行，不代表真实研究结论。")}</div>}<article className="markdown document-article"><ReactMarkdown disallowedElements={['img']} remarkPlugins={[remarkGfm]} components={{ a: ({ children, href }) => <a href={href} target="_blank" rel="noreferrer">{children}</a> }}>{doc.content}</ReactMarkdown></article></>;
}
