import {useCallback,useState} from 'react';
import {ArrowUpToLine,CalendarDays,CalendarRange,CalendarX,ChevronRight,Circle,Copy,FileText,ListPlus,MoveRight,Sun,Sunrise,Tag,Trash2,XSquare,Pencil} from 'lucide-react';
import ContextMenu,{pointRect} from './context-menu';
import type {MenuPoint} from './context-menu';
import {Field,Modal} from './ui';
import type {Entry,TodoList} from './planner-types';
import {addDays,entryBody,localDay,localInput} from './planner-types';
import {api} from './api';
import {tr} from './i18n';
export default function TaskActions({entry,entries,point,lists,close,refresh,open,child,removed}:{entry:Entry;entries?:Entry[];point:MenuPoint;lists:TodoList[];close:()=>void;refresh:()=>void;open:()=>void;child:()=>void;removed:(entry:Entry)=>void}){
 const targets=entries?.length?entries:[entry],multiple=targets.length>1,readOnly=targets.some(item=>item.read_only);
 const [changes,setChanges]=useState<Partial<Entry>>({}),[childTitle,setChildTitle]=useState('');
 const [view,setView]=useState('menu'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tags,setTags]=useState((entry.tags||[]).join(','));
 const [allDay,setAllDay]=useState(entry.all_day),[start,setStart]=useState(entry.start||new Date().toISOString()),[end,setEnd]=useState(entry.end||new Date(Date.now()+3600000).toISOString());
 const dismiss=useCallback(()=>{if(!busy)close();},[busy,close]);
 async function run(action:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await action();refresh();close();}catch(e){setError((e as Error).message);refresh();}finally{setBusy(false);}}
 async function each(action:(item:Entry)=>Promise<unknown>){const errors:string[]=[];for(const item of targets){try{await action(item);}catch(e){errors.push(item.title+': '+(e as Error).message);}}if(errors.length)throw new Error(`已处理 ${targets.length-errors.length}/${targets.length} 项；${errors.join('；')}`);}
 const save=(changes:Partial<Entry>)=>run(()=>each(item=>api(`/planner/entries/${item.id}`,'PUT',entryBody({...item,...changes}))));
 if(view==='edit'||view==='child')return <Modal title={tr(view==='edit'?'批量编辑任务':'添加子任务')} anchor={pointRect(point)} nonModal close={dismiss} outside={dismiss}><form className="planner-form" onSubmit={e=>{e.preventDefault();if(view==='edit')void save(changes);else void run(()=>each(item=>api('/planner/entries','POST',{title:childTitle.trim(),list_id:item.list_id,parent_id:item.id})));}}><small>{tr('已选择 {0} 项',[targets.length])}</small>{view==='child'?<Field label={tr('标题')}><input required value={childTitle} onChange={e=>setChildTitle(e.target.value)}/></Field>:<>{(['title','notes','location'] as const).map(key=><Field key={key} label={tr({title:'标题',notes:'备注',location:'地点'}[key])}><input placeholder={tr('未修改的字段保持原样')} value={changes[key]??''} onChange={e=>setChanges({...changes,[key]:e.target.value})}/></Field>)}</>}{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy||readOnly||view==='edit'&&!Object.keys(changes).length}>{tr('保存')}</button></form></Modal>;
 function datePreset(days:number|null){if(days===null){void save({start:null,end:null,all_day:false});return;}const day=addDays(new Date(),days);void save({start:localDay(day),end:localDay(addDays(day,1)),all_day:true});}
 if(view==='date'||view==='tags')return <Modal title={tr(view==='date'?'详细日期':'标签')} anchor={pointRect(point)} nonModal close={dismiss} outside={dismiss}><form className="planner-form" onSubmit={e=>{e.preventDefault();if(view==='tags')void save({tags:tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean)});else if(new Date(end)<=new Date(start))setError(tr('结束时间必须晚于开始时间'));else void save({start,end,all_day:allDay});}}>{view==='tags'?<Field label={tr('标签')} hint={tr('用逗号分隔，最多 20 个标签')}><input autoFocus aria-label={tr('标签')} value={tags} onChange={e=>setTags(e.target.value)}/></Field>:<><label className="planner-checkbox"><input type="checkbox" checked={allDay} onChange={e=>{const all=e.target.checked;setAllDay(all);if(all){const day=localDay(new Date(start));setStart(day);setEnd(localDay(addDays(new Date(day+'T12:00:00'),1)));}else{setStart(new Date(start+'T09:00:00').toISOString());setEnd(new Date(start+'T10:00:00').toISOString());}}}/>{tr('全天')}</label><Field label={tr('开始')}><input required type={allDay?'date':'datetime-local'} value={allDay?start:localInput(start)} onChange={e=>{if(e.target.value)setStart(allDay?e.target.value:new Date(e.target.value).toISOString());}}/></Field><Field label={tr(allDay?'结束（不含当天）':'结束')}><input required type={allDay?'date':'datetime-local'} value={allDay?end:localInput(end)} onChange={e=>{if(e.target.value)setEnd(allDay?e.target.value:new Date(e.target.value).toISOString());}}/></Field></>}{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}>{tr('保存')}</button></form></Modal>;
 return <ContextMenu point={point} close={dismiss} label={tr('任务选项')}>{view==='move'?<><button role="menuitem" onClick={()=>setView('menu')}>← {tr('返回')}</button>{lists.filter(l=>!l.read_only).map(l=><button role="menuitem" key={l.id} disabled={busy||readOnly} onClick={()=>void save({list_id:l.id})}><Circle size={14} color={l.color}/>{l.name}</button>)}</>:<><div className="menu-heading">{tr('日期')}</div><div className="menu-icon-row">{[{label:'今天',icon:Sun,days:0},{label:'明天',icon:Sunrise,days:1},{label:'下周',icon:CalendarRange,days:7},{label:'本周末',icon:CalendarDays,days:(6-new Date().getDay()+7)%7},{label:'移除日期',icon:CalendarX,days:null}].map(p=><button key={p.label} role="menuitem" aria-label={tr(p.label)} title={tr(p.label)} disabled={busy||readOnly} onClick={()=>datePreset(p.days)}><p.icon size={21}/></button>)}</div><button role="menuitem" disabled={readOnly} onClick={()=>setView('date')}><CalendarDays size={17}/><span>{tr('详细日期')}</span><ChevronRight size={15}/></button><div className="menu-heading">{tr('优先级')}</div><div className="menu-icon-row">{(['high','medium','low','none'] as const).map(p=><button role="menuitem" aria-label={tr({high:'高优先级',medium:'中优先级',low:'低优先级',none:'无优先级'}[p])} aria-pressed={entry.priority===p} disabled={busy||readOnly} key={p} onClick={()=>void save({priority:p})}><Circle size={20} className={`priority-${p}`} fill={p==='none'?'none':'currentColor'}/></button>)}</div><hr/>
 <button role="menuitem" onClick={()=>{if(multiple)setView('edit');else{close();open();}}}><Pencil size={17}/>{tr('编辑详情')}</button>
 <button role="menuitem" disabled={readOnly||targets.some(item=>item.is_note)} onClick={()=>{if(multiple)setView('child');else{close();child();}}}><ListPlus size={18}/>{tr('添加子任务')}</button>
 <button role="menuitem" disabled={busy||readOnly} onClick={()=>void save({pinned:!entry.pinned})}><ArrowUpToLine size={18}/>{tr(entry.pinned?'取消置顶':'置顶')}</button>
 <button role="menuitem" disabled={busy||readOnly||entry.is_note} onClick={()=>void save({cancelled:!entry.cancelled,completed:false})}><XSquare size={18}/>{tr(entry.cancelled?'恢复任务':'放弃')}</button>
 <button role="menuitem" disabled={readOnly} onClick={()=>setView('move')}><MoveRight size={18}/><span>{tr('移动到')}</span><ChevronRight size={15}/></button>
 <button role="menuitem" disabled={readOnly} onClick={()=>setView('tags')}><Tag size={18}/>{tr('标签')}</button>
 <button role="menuitem" disabled={busy} onClick={()=>void run(()=>each(item=>{const {revision:_,...body}=entryBody({...item,title:item.title+tr('（副本）'),parent_id:'',pinned:false,completed:false,cancelled:false});return api('/planner/entries','POST',body);}))}><Copy size={18}/>{tr('创建副本')}</button>
 <button role="menuitem" disabled={busy||readOnly} onClick={()=>void save({is_note:!entry.is_note,completed:false,cancelled:false})}><FileText size={18}/>{tr(entry.is_note?'转换为任务':'转换为笔记')}</button>
 <hr/><button role="menuitem" className="danger-text" disabled={busy||readOnly} onClick={()=>void run(()=>each(async item=>{await api(`/planner/entries/${item.id}?revision=${item.revision}`,'DELETE');removed(item);}))}><Trash2 size={18}/>{tr('删除')}</button></>}{error&&<p role="alert">{error}</p>}</ContextMenu>;
}
